name: Auto update (every 3 days)

on:
  schedule:
    - cron: '0 3 */3 * *'   # ~09:00 Asia/Dhaka
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure git author
        run: |
          AUTHOR_NAME="${{ github.actor }}"
          AUTHOR_EMAIL="${{ secrets.NOREPLY_EMAIL }}"
          if [ -z "$AUTHOR_EMAIL" ]; then
            AUTHOR_EMAIL="${{ github.actor }}@users.noreply.github.com"
          fi
          git config user.name  "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
          echo "Author: $AUTHOR_NAME <$AUTHOR_EMAIL>"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Rotate accent color in config.json
        run: |
          set -e
          if [ ! -f config.json ]; then
            echo '{"accent":"#2DD4BF","palette":["#2DD4BF","#60A5FA","#A78BFA","#F472B6","#F87171","#F59E0B"]}' > config.json
          fi

          PALETTE=$(jq -r '.palette[]?' config.json)
          if [ -z "$PALETTE" ]; then
            PALETTE="#2DD4BF
#60A5FA
#A78BFA
#F472B6
#F87171
#F59E0B"
          fi

          CURRENT=$(jq -r '.accent // empty' config.json)
          ARR=($PALETTE)
          IDX=-1
          for i in "${!ARR[@]}"; do
            if [ "${ARR[$i]}" = "$CURRENT" ]; then IDX=$i; break; fi
          done
          NEXT="${ARR[$(( (IDX + 1) % ${#ARR[@]} ))]}"

          TMP=$(mktemp)
          jq --arg nxt "$NEXT" '.accent = $nxt' config.json > "$TMP" && mv "$TMP" config.json
          echo "accent: ${CURRENT:-<none>} -> $NEXT"

      - name: Commit & push
        run: |
          git add config.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: scheduled update"
          git push
