name: Auto update (every 3 days)

on:
  schedule:
    - cron: '0 3 */3 * *'   # ~09:00 Asia/Dhaka
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Configure git author (use GitHub noreply automatically)
        env:
          ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          ID=$(curl -fsSL -H "Authorization: Bearer $GH_TOKEN" https://api.github.com/users/$ACTOR | jq -r '.id')
          EMAIL="${ID}+${ACTOR}@users.noreply.github.com"
          git config user.name  "$ACTOR"
          git config user.email "$EMAIL"
          echo "Using author: $ACTOR <$EMAIL>"

      - name: Rotate accent color in config.json
        run: |
          set -e
          if [ ! -f config.json ]; then
            cat > config.json <<'JSON'
{
  "accent": "#2DD4BF",
  "palette": ["#2DD4BF","#60A5FA","#A78BFA","#F472B6","#F87171","#F59E0B"]
}
JSON
          fi

          PALETTE=$(jq -r '.palette[]?' config.json)
          if [ -z "$PALETTE" ]; then
            PALETTE="#2DD4BF
#60A5FA
#A78BFA
#F472B6
#F87171
#F59E0B"
          fi

          CURRENT=$(jq -r '.accent // empty' config.json)
          ARR=($PALETTE)
          IDX=-1
          for i in "${!ARR[@]}"; do
            if [ "${ARR[$i]}" = "$CURRENT" ]; then IDX=$i; break; fi
          done
          NEXT="${ARR[$(( (IDX + 1) % ${#ARR[@]} ))]}"

          TMP=$(mktemp)
          jq --arg nxt "$NEXT" '.accent = $nxt' config.json > "$TMP" && mv "$TMP" config.json
          echo "accent: ${CURRENT:-<none>} -> $NEXT"

      - name: Commit & push
        run: |
          git add config.json
          if git diff --cached --quiet; then
            echo 'No changes to commit.'
            exit 0
          fi
          git commit -m 'chore: scheduled update'
          git push
